name: Update Electricity Prices
on:
  schedule:
    - cron: '0 1 * * *' # Se ejecuta una vez al día a la 01:00 AM UTC
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/data/luz.json
          git commit -m "⚡ Auto-update: Electricity Prices [$(date +'%Y-%m-%d')]" || exit 0
          git push
